const { Pool } = require('pg');
require('dotenv').config();

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

// Dates are for 2026 unless noted. Hindu lunar calendar festivals shift yearly.
const festivals = [

  // ── JANUARY ──────────────────────────────────────────────────────────────
  {
    name: 'Makar Sankranti',
    local_name: 'Uttarayan / Pongal / Lohri',
    start_date: '2026-01-14',
    end_date: '2026-01-15',
    city: null,
    region: 'Nationwide',
    state: 'All India',
    festival_type: 'Hindu / Harvest',
    significance: 'Solar harvest festival marking the sun\'s entry into Capricorn. Kite flying in Gujarat (Uttarayan), Pongal in Tamil Nadu, Lohri in Punjab. One of the few fixed-date Hindu festivals.',
    crowd_level: 'high',
    travel_impact: 'Ahmedabad skies fill with kites — hotels book out months ahead. Domestic flights surge. Book early for Gujarat.',
    notes: 'Best experienced in Ahmedabad for kite festival or Varanasi for Ganga ghats celebrations.',
    recurring: true
  },
  {
    name: 'Vasant Panchami',
    local_name: 'Saraswati Puja',
    start_date: '2026-02-01',
    end_date: '2026-02-01',
    city: 'Kolkata',
    region: 'Eastern India',
    state: 'West Bengal',
    festival_type: 'Hindu',
    significance: 'Celebration of Goddess Saraswati (knowledge, arts, learning). Schools and universities worship Saraswati idols. People wear yellow. Marks the onset of spring.',
    crowd_level: 'medium',
    travel_impact: 'Minimal travel disruption. Strong cultural atmosphere in Kolkata and Varanasi.',
    notes: 'Yellow is the color of the day — guests should wear yellow for an authentic experience.',
    recurring: true
  },

  // ── FEBRUARY ─────────────────────────────────────────────────────────────
  {
    name: 'Khajuraho Dance Festival',
    local_name: null,
    start_date: '2026-02-20',
    end_date: '2026-02-26',
    city: 'Khajuraho',
    region: 'Bundelkhand',
    state: 'Madhya Pradesh',
    festival_type: 'Cultural / Classical Dance',
    significance: 'Week-long classical Indian dance festival held against the backdrop of the UNESCO-listed Khajuraho temples. Features Bharatanatyam, Kathak, Odissi, Manipuri, Kuchipudi.',
    crowd_level: 'medium',
    travel_impact: 'Khajuraho fills with arts patrons and tourists. Book accommodation in advance.',
    notes: 'Outstanding pairing with a broader MP cultural itinerary. Exact dates shift slightly each year.',
    recurring: true
  },
  {
    name: 'Mahashivratri',
    local_name: 'Maha Shivaratri',
    start_date: '2026-02-18',
    end_date: '2026-02-19',
    city: 'Varanasi',
    region: 'Uttar Pradesh',
    state: 'Uttar Pradesh',
    festival_type: 'Hindu',
    significance: 'The great night of Shiva. All-night vigils, abhishek pujas, and processions at Shiva temples across India. Varanasi and Ujjain are the epicentres.',
    crowd_level: 'very high',
    travel_impact: 'Massive pilgrim influx in Varanasi, Ujjain, Somnath, Pashupatinath (Nepal). Hotels sell out. Ghats extremely crowded overnight.',
    notes: 'Extraordinary spiritual experience but logistics are demanding. Pre-book everything. Also spectacular in Ujjain.',
    recurring: true
  },

  // ── MARCH ────────────────────────────────────────────────────────────────
  {
    name: 'Lathmar Holi',
    local_name: null,
    start_date: '2026-03-05',
    end_date: '2026-03-07',
    city: 'Barsana',
    region: 'Braj Mandal',
    state: 'Uttar Pradesh',
    festival_type: 'Hindu / Cultural',
    significance: 'Women of Barsana beat men from Nandgaon with lathis (sticks) in a playful re-enactment of Krishna and Radha\'s legend. One of India\'s most unique and photogenic celebrations.',
    crowd_level: 'very high',
    travel_impact: 'Small town, enormous crowds. Base in Mathura or Agra. Day trip with local guide essential.',
    notes: 'Spectacular for photography. Guests must be prepared for colour powder, noise, and tight crowds. Not for the faint-hearted.',
    recurring: true
  },
  {
    name: 'Holi',
    local_name: 'Phalguna Purnima',
    start_date: '2026-03-13',
    end_date: '2026-03-14',
    city: 'Mathura',
    region: 'Braj Mandal',
    state: 'Uttar Pradesh',
    festival_type: 'Hindu',
    significance: 'Festival of colours celebrating the victory of good over evil and the arrival of spring. Holika Dahan bonfire on the eve, colour play the next day. Most vibrant in Mathura, Vrindavan, Varanasi, and Jaipur.',
    crowd_level: 'very high',
    travel_impact: 'Transport disruptions common. Many businesses closed on main day. Domestic travel surges in the week prior.',
    notes: 'Avoid white clothing — everything gets coloured. Natural colour powder available at better venues. Vrindavan flower holi (Phoolon wali Holi) is a gentler alternative.',
    recurring: true
  },
  {
    name: 'Vrindavan Flower Holi',
    local_name: 'Phoolon wali Holi',
    start_date: '2026-03-10',
    end_date: '2026-03-10',
    city: 'Vrindavan',
    region: 'Braj Mandal',
    state: 'Uttar Pradesh',
    festival_type: 'Hindu / Cultural',
    significance: 'Flower petals instead of coloured powder are showered on devotees at Banke Bihari temple and Radha Raman temple. A refined, fragrant, and deeply devotional version of Holi.',
    crowd_level: 'high',
    travel_impact: 'Day-trip crowds from Delhi and Agra. Roads to Vrindavan congested.',
    notes: 'Perfect for B&B clients who want the Holi experience without harsh chemical colours. Pair with temple circuit.',
    recurring: true
  },
  {
    name: 'Ram Navami',
    local_name: null,
    start_date: '2026-03-28',
    end_date: '2026-03-28',
    city: 'Ayodhya',
    region: 'Uttar Pradesh',
    state: 'Uttar Pradesh',
    festival_type: 'Hindu',
    significance: 'Birth anniversary of Lord Ram. Ayodhya is the principal site — Ram Lalla temple, Saryu river aarti, and grand processions. Also celebrated in Rameswaram and Varanasi.',
    crowd_level: 'very high',
    travel_impact: 'Ayodhya is extremely congested. The new Ram Mandir has dramatically increased pilgrimage volume since 2024.',
    notes: 'Since the Ram Mandir consecration (Jan 2024), Ram Navami in Ayodhya is now one of India\'s largest pilgrimages. Plan transport carefully.',
    recurring: true
  },

  // ── APRIL ────────────────────────────────────────────────────────────────
  {
    name: 'Baisakhi',
    local_name: 'Vaisakhi',
    start_date: '2026-04-13',
    end_date: '2026-04-14',
    city: 'Amritsar',
    region: 'Punjab',
    state: 'Punjab',
    festival_type: 'Sikh / Harvest',
    significance: 'Sikh New Year and harvest festival. The founding of the Khalsa by Guru Gobind Singh in 1699. Grand celebrations at Harmandir Sahib (Golden Temple) with langar, kirtan, and processions (nagar kirtan).',
    crowd_level: 'very high',
    travel_impact: 'Amritsar hotels at capacity. Book 3+ months ahead. Trains from Delhi packed.',
    notes: 'Extraordinarily moving experience at the Golden Temple. Langar serves hundreds of thousands.',
    recurring: true
  },
  {
    name: 'Thrissur Pooram',
    local_name: null,
    start_date: '2026-04-28',
    end_date: '2026-04-29',
    city: 'Thrissur',
    region: 'Central Kerala',
    state: 'Kerala',
    festival_type: 'Hindu / Temple',
    significance: 'Arguably India\'s grandest temple festival. Two groups of caparisoned elephants (up to 30 per side) face off in a display of parasols, whisks, and fans to the beat of enormous percussion ensembles (panchavadyam). Climaxes with a fireworks display.',
    crowd_level: 'very high',
    travel_impact: 'Thrissur city brought to a standstill. Over a million spectators. Book Kochi/Thrissur accommodation months ahead.',
    notes: 'Non-negotiable bucket-list India experience. The percussion and fireworks are extraordinary. Exact date set annually by the Thrissur Vadakkunathan temple.',
    recurring: true
  },

  // ── MAY ──────────────────────────────────────────────────────────────────
  {
    name: 'Buddha Purnima',
    local_name: 'Vesak',
    start_date: '2026-05-12',
    end_date: '2026-05-12',
    city: 'Bodh Gaya',
    region: 'Bihar',
    state: 'Bihar',
    festival_type: 'Buddhist',
    significance: 'Birth, enlightenment, and death of Gautama Buddha all commemorated on the same full moon. Bodh Gaya (site of enlightenment), Sarnath (first sermon), and Kushinagar (parinirvana) are the pilgrimage centres.',
    crowd_level: 'high',
    travel_impact: 'International Buddhist delegations from Thailand, Japan, Sri Lanka, Myanmar. Hotels in Bodh Gaya fill early.',
    notes: 'Deeply peaceful and spiritual atmosphere. The Mahabodhi Temple is illuminated. Pair with Varanasi/Sarnath circuit.',
    recurring: true
  },

  // ── JUNE / JULY ──────────────────────────────────────────────────────────
  {
    name: 'Rath Yatra',
    local_name: 'Chariot Festival of Lord Jagannath',
    start_date: '2026-06-21',
    end_date: '2026-06-29',
    city: 'Puri',
    region: 'Odisha Coast',
    state: 'Odisha',
    festival_type: 'Hindu / Vaishnava',
    significance: 'Three enormous wooden chariots carrying deities Jagannath, Balabhadra, and Subhadra are pulled by hundreds of thousands of devotees through the streets of Puri. One of the oldest and largest religious processions on Earth.',
    crowd_level: 'very high',
    travel_impact: 'Puri overwhelmed. Over a million pilgrims. Book many months ahead. Puri beach hotels at a premium.',
    notes: 'UNESCO Intangible Cultural Heritage. Chariots take 2-3 days to travel 3km. Extraordinary spectacle. Exact date determined by Odia lunar calendar — confirm annually.',
    recurring: true
  },
  {
    name: 'Hemis Festival',
    local_name: null,
    start_date: '2026-07-01',
    end_date: '2026-07-02',
    city: 'Hemis',
    region: 'Ladakh',
    state: 'Ladakh',
    festival_type: 'Buddhist / Tibetan',
    significance: 'Largest monastic festival in Ladakh. Hemis Monastery\'s monks perform Cham masked dances celebrating Guru Padmasambhava\'s birth. Every 12 years the massive Thangka is unfurled (next: 2029).',
    crowd_level: 'high',
    travel_impact: 'Hemis village inaccessible by car on festival days. Leh hotels fill. Acclimatisation time needed before travel to 3600m.',
    notes: 'Combine with Leh, Pangong Lake, Nubra Valley for a complete Ladakh itinerary. International tourists and Tibetan Buddhist pilgrims both attend.',
    recurring: true
  },

  // ── AUGUST ───────────────────────────────────────────────────────────────
  {
    name: 'Janmashtami',
    local_name: 'Krishna Jayanti',
    start_date: '2026-08-22',
    end_date: '2026-08-23',
    city: 'Mathura',
    region: 'Braj Mandal',
    state: 'Uttar Pradesh',
    festival_type: 'Hindu / Vaishnava',
    significance: 'Celebration of Krishna\'s birth at midnight. Mathura (birthplace) and Vrindavan are the epicentres. Dahi Handi — human pyramids to break a clay pot of yogurt — is spectacular in Mumbai.',
    crowd_level: 'very high',
    travel_impact: 'Mathura-Vrindavan corridor overwhelmed. Midnight events mean all-night operations. Mumbai\'s Dahi Handi draws enormous street crowds.',
    notes: 'ISKCON temples worldwide celebrate grandly. Vrindavan\'s Banke Bihari temple is the most atmospheric. Mumbai Dahi Handi is a completely different energy — loud, competitive, festive.',
    recurring: true
  },
  {
    name: 'Onam',
    local_name: null,
    start_date: '2026-08-27',
    end_date: '2026-09-05',
    city: null,
    region: 'Kerala',
    state: 'Kerala',
    festival_type: 'Hindu / Harvest',
    significance: 'Kerala\'s harvest festival celebrating King Mahabali\'s annual return. Ten days of celebrations featuring pookalam (flower carpets), Vallam Kali (snake boat races), Pulikali (tiger dance), and the grand Onam Sadya feast (26+ dishes on a banana leaf).',
    crowd_level: 'high',
    travel_impact: 'Boats races at Alappuzha (Alleppey) draw enormous crowds. Domestic tourism peaks. Houseboat bookings surge.',
    notes: 'Thiruvonam (main day) is the 10th day. Nehru Trophy Boat Race (nearby date) is spectacular. Excellent time for Kerala houseboat + backwaters itinerary.',
    recurring: true
  },

  // ── SEPTEMBER ────────────────────────────────────────────────────────────
  {
    name: 'Ganesh Chaturthi',
    local_name: 'Ganeshotsav',
    start_date: '2026-09-06',
    end_date: '2026-09-16',
    city: 'Mumbai',
    region: 'Maharashtra',
    state: 'Maharashtra',
    festival_type: 'Hindu',
    significance: '10-day festival honouring Ganesha. Massive clay idols installed in homes and public pandals across Maharashtra, immersed in the sea on Anant Chaturdashi. Mumbai\'s Lalbaugcha Raja draws millions. Pune equally spectacular.',
    crowd_level: 'very high',
    travel_impact: 'Mumbai transport severely impacted on immersion day (Day 10). Roads blocked for processions. Coastal areas crowded.',
    notes: 'The immersion procession on the final day is extraordinary — music, dance, colour, devotion. Best viewed from upper floors or a guided vantage point.',
    recurring: true
  },

  // ── OCTOBER ──────────────────────────────────────────────────────────────
  {
    name: 'Navratri',
    local_name: 'Navaratri',
    start_date: '2026-10-08',
    end_date: '2026-10-17',
    city: null,
    region: 'Nationwide',
    state: 'All India',
    festival_type: 'Hindu',
    significance: 'Nine nights dedicated to Goddess Durga in her nine forms. Kolkata\'s Durga Puja is the cultural highpoint. Gujarat celebrates with Garba and Dandiya Raas dancing all night. Vaishno Devi in Jammu sees peak pilgrimage.',
    crowd_level: 'very high',
    travel_impact: 'Kolkata, Ahmedabad, Vadodara, Varanasi all packed. Flights and hotels at premium. Book 4+ months ahead for Kolkata Durga Puja.',
    notes: 'Two major distinct experiences: Kolkata (artistic idol installations, cultural performances) vs Gujarat (all-night dancing). Both extraordinary. Dussehra on Day 10.',
    recurring: true
  },
  {
    name: 'Durga Puja',
    local_name: 'Mahalaya to Bijoya Dashami',
    start_date: '2026-10-13',
    end_date: '2026-10-17',
    city: 'Kolkata',
    region: 'West Bengal',
    state: 'West Bengal',
    festival_type: 'Hindu',
    significance: 'Kolkata transforms into the world\'s largest open-air art exhibition. Thousands of elaborately themed pandals (temporary temples) with Durga idols, climaxing with immersion (Bisarjan) in the Hooghly River. UNESCO Intangible Cultural Heritage (2021).',
    crowd_level: 'very high',
    travel_impact: 'Kolkata hotels completely sold out 6 months ahead. Pandal-hopping till 4am. City never sleeps for 5 days.',
    notes: 'Book a pandal-hopping guide to navigate the best installations. Heritage neighbourhoods (Kumartuli, North Kolkata) offer the most authentic atmosphere. Not to be missed.',
    recurring: true
  },
  {
    name: 'Dussehra',
    local_name: 'Vijayadashami',
    start_date: '2026-10-18',
    end_date: '2026-10-18',
    city: 'Mysuru',
    region: 'Karnataka',
    state: 'Karnataka',
    festival_type: 'Hindu',
    significance: 'Victory of Ram over Ravana. Mysuru (Mysore) hosts India\'s grandest Dussehra — a royal procession of caparisoned elephants, illuminated Mysore Palace, and burning of Ravana effigies. Varanasi\'s Ramlila and Delhi\'s effigy burning also spectacular.',
    crowd_level: 'very high',
    travel_impact: 'Mysuru hotel prices triple. Bengaluru-Mysuru highway congested. Book months ahead. Delhi Ramlila Maidan very crowded.',
    notes: 'Mysore Palace is lit with 100,000 bulbs — a sight unlike anything else in India. The elephant procession is magnificent.',
    recurring: true
  },

  // ── NOVEMBER ─────────────────────────────────────────────────────────────
  {
    name: 'Diwali',
    local_name: 'Deepavali / Festival of Lights',
    start_date: '2026-10-28',
    end_date: '2026-11-01',
    city: null,
    region: 'Nationwide',
    state: 'All India',
    festival_type: 'Hindu / Jain / Sikh',
    significance: 'India\'s most celebrated festival — five days of lights, fireworks, sweets, and family. Jaipur, Varanasi (Ganga aarti), Amritsar (Golden Temple), and Ayodhya (diyas along the Saryu) offer transformative experiences.',
    crowd_level: 'very high',
    travel_impact: 'Nationwide transport surge. Trains booked weeks ahead. Air quality drops in north India from fireworks. Hotels at premium everywhere.',
    notes: 'Ayodhya now sets world records for Diwali diyas on the Saryu ghats. Varanasi ghats equally beautiful. Jaipur has exceptional sweets, bazaars and private haveli celebrations. Book B&B clients into heritage properties for rooftop views.',
    recurring: true
  },
  {
    name: 'Dev Deepawali',
    local_name: 'Deva Diwali',
    start_date: '2026-11-11',
    end_date: '2026-11-11',
    city: 'Varanasi',
    region: 'Uttar Pradesh',
    state: 'Uttar Pradesh',
    festival_type: 'Hindu',
    significance: 'Kartik Purnima (full moon). The gods themselves are said to descend to bathe in the Ganga. The 84 ghats of Varanasi are lined with a million earthen lamps (diyas). Boat processions, Ganga aarti at scale, and fireworks. More intimate and spiritual than Diwali.',
    crowd_level: 'very high',
    travel_impact: 'Varanasi\'s biggest crowd event of the year — larger than Diwali. Hotels sold out months ahead. River boats essential.',
    notes: 'Premium experience: charter a private boat at dusk to float along the illuminated ghats. The silence broken only by temple bells and the river is transcendent. One of B&B\'s top signature experiences.',
    recurring: true
  },
  {
    name: 'Pushkar Camel Fair',
    local_name: 'Pushkar Mela',
    start_date: '2026-11-06',
    end_date: '2026-11-14',
    city: 'Pushkar',
    region: 'Rajasthan',
    state: 'Rajasthan',
    festival_type: 'Hindu / Cultural / Trade',
    significance: 'One of the world\'s largest camel fairs — 50,000+ camels, horses, and livestock traded. Coincides with Kartik Purnima. Sacred Pushkar Lake bathing, Brahma temple worship, folk musicians, acrobats, and an explosion of colour.',
    crowd_level: 'very high',
    travel_impact: 'Pushkar overflows. Tented camps and heritage hotels 100% booked months ahead. Ajmer used as overflow base.',
    notes: 'Book luxury tented camps for best experience (Sujan, The Oberoi, and others operate camps). The dunes at dawn with camels silhouetted is iconic.',
    recurring: true
  },
  {
    name: 'Hornbill Festival',
    local_name: null,
    start_date: '2026-12-01',
    end_date: '2026-12-10',
    city: 'Kisama',
    region: 'Nagaland',
    state: 'Nagaland',
    festival_type: 'Cultural / Tribal',
    significance: 'Festival of Festivals — all 17 major tribes of Nagaland perform traditional dances, display warrior regalia, demonstrate indigenous crafts and cuisine at the Naga Heritage Village in Kisama, near Kohima.',
    crowd_level: 'medium',
    travel_impact: 'Kisama and Kohima fill with domestic and international visitors. Book accommodation early. Dimapur is the nearest airport.',
    notes: 'Completely unlike any other Indian festival experience. Morung (tribal dormitory) architecture, traditional tattoos, smoked meat, and rice beer. A profound encounter with Northeast India\'s cultures.',
    recurring: true
  },

  // ── DECEMBER ─────────────────────────────────────────────────────────────
  {
    name: 'Goa Carnival',
    local_name: 'Carnaval de Goa',
    start_date: '2027-02-14',
    end_date: '2027-02-17',
    city: 'Panaji',
    region: 'Goa',
    state: 'Goa',
    festival_type: 'Catholic / Cultural',
    significance: 'Portuguese-heritage carnival — three days of floats, costumes, music, and revelry on the streets of Panaji, Margao, Mapusa, and Vasco. King Momo presides. Unique fusion of Indian and Lusophone cultures.',
    crowd_level: 'high',
    travel_impact: 'Post-peak season; accommodation available but filling for the dates. Goa is still warm and pleasant.',
    notes: 'Dates are for 2027 (pre-Lent). Good add-on for clients extending a Kerala-Goa itinerary.',
    recurring: true
  },
  {
    name: 'Rann Utsav',
    local_name: null,
    start_date: '2026-11-01',
    end_date: '2027-02-28',
    city: 'Dhordo',
    region: 'Kutch',
    state: 'Gujarat',
    festival_type: 'Cultural / Tourism',
    significance: 'Three-month celebration on the white salt desert of the Rann of Kutch under the full moon. Luxury tented city, folk artists, artisans, Kutchi embroidery, camel rides, and stargazing on the vast white expanse.',
    crowd_level: 'medium',
    travel_impact: 'Bhuj is the base. Full moon nights are peak — book tented camps well ahead.',
    notes: 'Ideal winter escape with strong artisan and cultural content. One of India\'s most curated tourism festivals. Kutchi handicrafts are world-class.',
    recurring: true
  },
  {
    name: 'Rajasthan International Folk Festival (RIFF)',
    local_name: null,
    start_date: '2026-10-23',
    end_date: '2026-10-27',
    city: 'Jodhpur',
    region: 'Rajasthan',
    state: 'Rajasthan',
    festival_type: 'Cultural / Music',
    significance: 'World music and folk arts festival held at the 15th-century Mehrangarh Fort. Indian folk musicians (Manganiyar, Langa, Kalbeliya) share the stage with international artists. Founded by Mick Jagger and Maharaja Gaj Singh II.',
    crowd_level: 'medium',
    travel_impact: 'Jodhpur\'s boutique hotels fill. International arts crowd.',
    notes: 'Outstanding for musically inclined B&B clients. Mehrangarh Fort setting is unmatched. Combines beautifully with Jaisalmer and Udaipur.',
    recurring: true
  },
  {
    name: 'Jaisalmer Desert Festival',
    local_name: null,
    start_date: '2026-02-12',
    end_date: '2026-02-14',
    city: 'Jaisalmer',
    region: 'Rajasthan',
    state: 'Rajasthan',
    festival_type: 'Cultural / Tourism',
    significance: 'Three-day celebration of Rajasthani folk culture against the backdrop of the Thar Desert and Sam sand dunes. Camel races, turban-tying contests, folk music, puppet shows, and the Miss Moomal beauty pageant.',
    crowd_level: 'medium',
    travel_impact: 'Jaisalmer hotels at peak. Dune camps fully booked.',
    notes: 'Timed around the full moon of Magh (Feb). A natural fit for Rajasthan itineraries.',
    recurring: true
  },
  {
    name: 'Hampi Utsav',
    local_name: 'Vijaya Utsav',
    start_date: '2026-11-06',
    end_date: '2026-11-08',
    city: 'Hampi',
    region: 'Karnataka',
    state: 'Karnataka',
    festival_type: 'Cultural / Heritage',
    significance: 'Three-day cultural festival at the UNESCO World Heritage ruins of the Vijayanagara Empire. Classical and folk dance, music performances, puppet shows, and heritage walks among the boulder-strewn landscape.',
    crowd_level: 'medium',
    travel_impact: 'Hampi and Hospet fill. Advance booking needed.',
    notes: 'Excellent timing with post-monsoon weather. Hampi is at its greenest. Temple illuminations are atmospheric.',
    recurring: true
  },
  {
    name: 'Konark Dance Festival',
    local_name: null,
    start_date: '2026-12-01',
    end_date: '2026-12-05',
    city: 'Konark',
    region: 'Odisha Coast',
    state: 'Odisha',
    festival_type: 'Cultural / Classical Dance',
    significance: 'Classical Indian dance performed against the backdrop of the 13th-century Sun Temple (UNESCO World Heritage Site). Features Odissi, Bharatanatyam, Kathak, Kuchipudi, Manipuri, and Mohiniattam.',
    crowd_level: 'medium',
    travel_impact: 'Bhubaneswar-Puri corridor is the base. Manageable crowds.',
    notes: 'Combine with Puri Jagannath Temple and Chilika Lake for a full Odisha coastal cultural circuit.',
    recurring: true
  },
  {
    name: 'Kumbh Mela — Prayagraj (Maha)',
    local_name: 'Maha Kumbh Mela',
    start_date: '2025-01-13',
    end_date: '2025-02-26',
    city: 'Prayagraj',
    region: 'Uttar Pradesh',
    state: 'Uttar Pradesh',
    festival_type: 'Hindu / Pilgrimage',
    significance: 'The largest human gathering on Earth. Held every 12 years at the Triveni Sangam (confluence of Ganga, Yamuna, and mythical Saraswati). 400–500 million attendees expected. Bathing on Shahi Snan (royal bath) dates is the spiritual pinnacle.',
    crowd_level: 'very high',
    travel_impact: 'All infrastructure in Prayagraj overwhelmed on major bathing dates. Private charter flights and luxury tent cities are the only way to manage logistics at this scale.',
    notes: 'Next Maha Kumbh is 2025 (note: dates are for 2025). Ardh Kumbh in 2028. Luxury operators set up tented cities 6+ months ahead. B&B should have a curated Kumbh offering for 2028.',
    recurring: true
  },
  {
    name: 'Bihu',
    local_name: 'Rongali Bihu',
    start_date: '2026-04-14',
    end_date: '2026-04-16',
    city: 'Guwahati',
    region: 'Assam',
    state: 'Assam',
    festival_type: 'Hindu / Harvest',
    significance: 'Assam\'s most important festival — Rongali (spring) Bihu marks the Assamese New Year and planting season. Bihu dance and music, feasting on rice cakes (pitha) and laru. Celebrated with enormous energy across Assam.',
    crowd_level: 'medium',
    travel_impact: 'Guwahati and Jorhat festive. Brahmaputra river cruises well-timed.',
    notes: 'Perfect complement to a Northeast India wildlife and culture itinerary (Kaziranga, Majuli Island, Ziro Valley).',
    recurring: true
  },
  {
    name: 'Losar',
    local_name: 'Tibetan New Year',
    start_date: '2026-02-28',
    end_date: '2026-03-02',
    city: 'Leh',
    region: 'Ladakh',
    state: 'Ladakh',
    festival_type: 'Buddhist / Tibetan',
    significance: 'Tibetan New Year celebrated across Ladakh, Spiti, Sikkim, and Dharamsala. Monastery rituals, Cham masked dances, archery, and traditional Ladakhi dress. More intimate than summer festivals as fewer tourists are present in winter Ladakh.',
    crowd_level: 'low',
    travel_impact: 'Winter Ladakh — Leh accessible only by air. Cold (-20°C possible). Intimate experience with locals.',
    notes: 'For adventurous B&B clients who want an authentic off-season Himalayan spiritual experience. Combine with frozen Zanskar Chadar trek if timing allows.',
    recurring: true
  },
  {
    name: 'Gangasagar Mela',
    local_name: null,
    start_date: '2026-01-14',
    end_date: '2026-01-15',
    city: 'Sagar Island',
    region: 'West Bengal',
    state: 'West Bengal',
    festival_type: 'Hindu / Pilgrimage',
    significance: 'Second-largest human gathering in India after Kumbh Mela. Pilgrims bathe at the confluence of the Ganga and the Bay of Bengal on Makar Sankranti. Said that one bath at Gangasagar equals 10 Kumbh baths.',
    crowd_level: 'very high',
    travel_impact: 'Ferry from Harwood Point overwhelmed. Kolkata also crowded. Logistics require advance planning.',
    notes: 'Deeply authentic pilgrimage with less tourist infrastructure than Kumbh. Sadhus and everyday pilgrims both present. Raw and powerful.',
    recurring: true
  },

  // ── CHUNK 6 ADDITIONS ────────────────────────────────────────────────────
  {
    name: 'Puri Beach Festival',
    local_name: null,
    start_date: '2026-11-05',
    end_date: '2026-11-09',
    city: 'Puri',
    region: 'Odisha Coast',
    state: 'Odisha',
    festival_type: 'Cultural / Art',
    significance: 'International sand sculpture festival on Puri beach coinciding with Diwali week. World-class sand artists create monumental sculptures. Set against the backdrop of the Bay of Bengal.',
    crowd_level: 'medium',
    travel_impact: 'Puri in good season. Manageable crowds. Bhubaneswar is the nearest airport.',
    notes: 'Natural pairing with Konark Sun Temple and Bhubaneswar temple circuit. Good add-on for Odisha-focused itineraries.',
    recurring: true
  },
  {
    name: 'Jaipur Literature Festival',
    local_name: 'JLF',
    start_date: '2027-01-28',
    end_date: '2027-02-01',
    city: 'Jaipur',
    region: 'Rajasthan',
    state: 'Rajasthan',
    festival_type: 'Cultural / Literary',
    significance: 'World\'s largest free literary festival. 500+ speakers — Nobel laureates, Booker Prize winners, journalists, filmmakers, and thinkers from across the globe. Held at the heritage Diggi Palace. Five days of sessions, debates, music, and Rajasthani hospitality.',
    crowd_level: 'high',
    travel_impact: 'Jaipur hotels at premium. Book 3+ months ahead. City festive and buzzing with an international crowd.',
    notes: 'Perfect anchor for a Rajasthan luxury trip — combine with Ranthambore tiger safari, Udaipur, and Jodhpur. Outstanding for intellectually curious B&B clients.',
    recurring: true
  },
  {
    name: 'Kumbh Mela Prayagraj Ardh',
    local_name: 'Ardh Kumbh Mela',
    start_date: '2027-01-13',
    end_date: '2027-02-26',
    city: 'Prayagraj',
    region: 'Uttar Pradesh',
    state: 'Uttar Pradesh',
    festival_type: 'Hindu / Pilgrimage',
    significance: 'Ardh (half) Kumbh Mela at the Triveni Sangam — confluence of the Ganga, Yamuna, and mythical Saraswati. The largest peaceful human gathering on Earth. Bathing on Shahi Snan (royal bath) dates is the spiritual pinnacle. Luxury Kumbh Village camps are the only way to experience this with comfort.',
    crowd_level: 'very high',
    travel_impact: 'All infrastructure overwhelmed on Shahi Snan dates. Private charter flights and luxury camp bookings must be made ONE YEAR ahead.',
    notes: 'Once-in-a-lifetime experience. Shahi Snan dates are the key planning anchor. Luxury tent city operators open booking 12 months out. B&B must have a curated Kumbh offering ready.',
    recurring: true
  },
  {
    name: 'Elephant Festival Jaipur',
    local_name: null,
    start_date: '2026-03-04',
    end_date: '2026-03-04',
    city: 'Jaipur',
    region: 'Rajasthan',
    state: 'Rajasthan',
    festival_type: 'Cultural / Royal',
    significance: 'Holi morning celebration at Chaugan Stadium. Elaborately decorated and painted elephants parade, play elephant polo, and compete in tug of war. A royal Rajasthani spectacle in the morning before the Holi colour chaos begins.',
    crowd_level: 'high',
    travel_impact: 'Jaipur busy with Holi visitors. The elephant festival is morning-only — colour play begins at midday.',
    notes: 'Pair with Jaipur Holi for a full-day experience. The festival has faced some animal welfare scrutiny — confirm it is running and ethical operators are involved each year.',
    recurring: true
  },
  {
    name: 'Nuakhai Juhar',
    local_name: 'Nuakhai',
    start_date: '2026-09-02',
    end_date: '2026-09-02',
    city: null,
    region: 'Western Odisha',
    state: 'Odisha',
    festival_type: 'Hindu / Harvest',
    significance: 'Odisha\'s most important harvest festival. The first rice of the new season is offered to Goddess Samaleswari before being eaten by the family. Sambalpuri dance, folk music, and feasting. An authentic local celebration — not a tourist festival.',
    crowd_level: 'low',
    travel_impact: 'Sambalpur and western Odisha districts are festive. No tourist infrastructure impact.',
    notes: 'Outstanding for culturally immersive itineraries. Guests are welcomed into family celebrations. Sambalpuri weave (ikat) shopping pairs naturally.',
    recurring: true
  },
  {
    name: 'Maha Shivaratri',
    local_name: 'Mahashivratri',
    start_date: '2026-02-15',
    end_date: '2026-02-16',
    city: null,
    region: 'Nationwide — especially Varanasi and Ujjain',
    state: 'All India',
    festival_type: 'Hindu',
    significance: 'The Great Night of Shiva. All-night vigil, fasting, and Shiva puja at temples nationwide. Varanasi ghats glow through the night with diyas and processions. Ujjain\'s Mahakaleshwar temple and Somnath in Gujarat are the other great centres.',
    crowd_level: 'very high',
    travel_impact: 'Varanasi and Ujjain overwhelmed. All accommodation requires advance booking. Overnight events mean transport chaos from midnight to dawn.',
    notes: 'Critical for BST planning context — Feb dates mean cold nights. Book 3 months ahead for Varanasi and Ujjain. The all-night atmosphere on the Varanasi ghats is extraordinary.',
    recurring: true
  },

  // ── CHUNK 4 ADDITIONS ────────────────────────────────────────────────────
  {
    name: 'Mysuru Dasara',
    local_name: 'Nadahabba',
    start_date: '2026-10-11',
    end_date: '2026-10-20',
    city: 'Mysuru',
    region: 'Karnataka',
    state: 'Karnataka',
    festival_type: 'Hindu / Royal',
    significance: 'Ten-day royal festival of the Wadiyar dynasty. Mysore Palace illuminated with 100,000 bulbs every evening. Vijayadashami culminates in the famous elephant procession carrying the golden howdah with the goddess Chamundeshwari. India\'s most regal festival.',
    crowd_level: 'very high',
    travel_impact: 'Mysuru hotels triple in price. Bengaluru-Mysuru highway severely congested. Book 3 months ahead minimum.',
    notes: 'The elephant procession on Vijayadashami is one of India\'s great spectacles. Palace illumination visible from miles away. Combine with Coorg and the Nagarhole wildlife reserve.',
    recurring: true
  },
  {
    name: 'Dussehra',
    local_name: 'Vijayadashami',
    start_date: '2026-10-20',
    end_date: '2026-10-20',
    city: null,
    region: 'Nationwide — especially Varanasi and Kullu Valley',
    state: 'All India',
    festival_type: 'Hindu',
    significance: 'Victory of Ram over Ravana — burning of giant Ravana effigies nationwide. Varanasi\'s Ramlila is a 31-day theatrical performance culminating in Ravana burning. In Kullu Valley, Himachal Pradesh, village deities are carried down from the mountains for a river gathering.',
    crowd_level: 'very high',
    travel_impact: 'Delhi, Varanasi, and Kullu all extremely crowded. Kullu Valley road access becomes slow. Delhi Ramlila Maidan draws hundreds of thousands.',
    notes: 'Varanasi Ramlila is 31 days of nightly performances — the effigy burning is the finale. Kullu Dussehra is entirely different in character — intimate, Himalayan, devotional. Two very different India experiences on the same day.',
    recurring: true
  },
  {
    name: 'Chhath Puja',
    local_name: 'Chhath',
    start_date: '2026-10-29',
    end_date: '2026-11-01',
    city: 'Patna',
    region: 'Bihar / Eastern UP',
    state: 'Bihar',
    festival_type: 'Hindu',
    significance: 'Ancient Vedic sun worship — one of Hinduism\'s most direct and demanding devotional practices. Devotees fast for 36 hours and stand in rivers for hours at sunset (Sandhya Arghya) and sunrise (Usha Arghya) offering prayers to the sun. Overwhelming to witness in Patna and Varanasi.',
    crowd_level: 'very high',
    travel_impact: 'Ghats in Patna and Varanasi become impassable. Massive return migration to Bihar from Delhi and Mumbai in the week prior, straining transport.',
    notes: 'No idol worship, no priest — just the devotee, the river, and the sun. Extraordinarily moving. One of the most authentic expressions of folk Hinduism. Not widely known to international travellers — a genuine hidden gem.',
    recurring: true
  },
  {
    name: 'Diwali',
    local_name: 'Deepavali / Festival of Lights',
    start_date: '2026-11-08',
    end_date: '2026-11-12',
    city: null,
    region: 'Nationwide — especially Varanasi and Ayodhya',
    state: 'All India',
    festival_type: 'Hindu / Jain / Sikh',
    significance: 'Festival of Lights — five days of diyas, fireworks, sweets, and family. The Ganga ghats in Varanasi are lined with diyas for miles. Ayodhya, post Ram Lalla consecration (2024), is now on an entirely different scale — world records for diya count on the Saryu ghats.',
    crowd_level: 'very high',
    travel_impact: 'Nationwide transport surge. Trains booked weeks ahead. Air quality drops sharply in north India from fireworks. All heritage hotels at premium.',
    notes: 'Ayodhya is now the most spectacular Diwali destination in India post-2024. Varanasi equally beautiful and more intimate. Book months ahead. B&B clients should be in heritage properties with rooftop or river views.',
    recurring: true
  },
  {
    name: 'Dev Deepawali',
    local_name: 'Deva Diwali / Kartik Purnima',
    start_date: '2026-11-24',
    end_date: '2026-11-24',
    city: 'Varanasi',
    region: 'Uttar Pradesh',
    state: 'Uttar Pradesh',
    festival_type: 'Hindu',
    significance: 'STAR FESTIVAL. Kartik Purnima — the gods are said to descend to bathe in the Ganga. All 84 ghats of Varanasi lit simultaneously with one million earthen lamps. More powerful and more spiritual than Diwali in Kashi. Boat processions, Ganga aarti at full scale, fireworks reflected in the river.',
    crowd_level: 'very high',
    travel_impact: 'Varanasi\'s single biggest crowd event. Hotels sold out months ahead. River boats essential — book weeks ahead.',
    notes: 'THE single most spectacular evening in the Varanasi calendar. Charter a private boat at dusk to float along the illuminated ghats. The silence broken only by temple bells and the river is transcendent. This is B&B\'s signature Varanasi moment.',
    recurring: true
  },

  // ── CHUNK 5 ADDITIONS ────────────────────────────────────────────────────
  {
    name: 'Pushkar Camel Fair',
    local_name: 'Pushkar Mela',
    start_date: '2026-11-17',
    end_date: '2026-11-24',
    city: 'Pushkar',
    region: 'Rajasthan',
    state: 'Rajasthan',
    festival_type: 'Hindu / Cultural / Trade',
    significance: 'World\'s largest camel fair — 50,000+ camels, horses, and livestock traded alongside Kartik Purnima pilgrimage. Camel races, folk performances, holy Pushkar Lake bathing, Brahma temple worship. One of the world\'s great travel experiences.',
    crowd_level: 'very high',
    travel_impact: 'Pushkar overflows. Luxury desert camps and heritage hotels 100% booked 3+ months ahead. Ajmer used as overflow base.',
    notes: 'Luxury tented camps (Sujan, The Oberoi) are the way to experience this. Dawn on the dunes with camels silhouetted against the sun is iconic. Book 3 months minimum ahead.',
    recurring: true
  },
  {
    name: 'Guru Nanak Jayanti',
    local_name: 'Gurpurab',
    start_date: '2026-11-23',
    end_date: '2026-11-23',
    city: 'Amritsar',
    region: 'Punjab',
    state: 'Punjab',
    festival_type: 'Sikh',
    significance: 'Birthday of Guru Nanak Dev Ji, founder of Sikhism. The Golden Temple (Harmandir Sahib) is at its most radiant — illuminated overnight, filled with kirtan, and serving langar to 100,000+ daily free of charge. Prabhat Pheris (pre-dawn processions) begin weeks before.',
    crowd_level: 'high',
    travel_impact: 'Amritsar fills with Sikh pilgrims from Punjab, the diaspora, and beyond. Book accommodation in advance.',
    notes: 'An extraordinarily moving experience. The langar (community kitchen) alone is humbling. Combine with Wagah Border ceremony for a full Amritsar day.',
    recurring: true
  },
  {
    name: 'Kolkata Film Festival',
    local_name: null,
    start_date: '2026-11-10',
    end_date: '2026-11-17',
    city: 'Kolkata',
    region: 'West Bengal',
    state: 'West Bengal',
    festival_type: 'Cultural / Cinema',
    significance: 'Asia\'s second oldest film festival. International film screenings, retrospectives, Bengali and Indian cinema celebration, panel discussions. Kolkata\'s intellectual and artistic life on full display — a fitting tribute to the city of Satyajit Ray.',
    crowd_level: 'medium',
    travel_impact: 'Venues across Kolkata. City is lively but not overwhelmed. Good shoulder-season timing.',
    notes: 'Perfect for culturally sophisticated B&B clients. Pairs with Kolkata heritage walks, Kumartuli potters\' quarter, and the Victoria Memorial.',
    recurring: true
  },
  {
    name: 'Theyyam Season',
    local_name: 'Theyyam',
    start_date: '2026-11-01',
    end_date: '2027-04-30',
    city: null,
    region: 'Malabar / North Kerala',
    state: 'Kerala',
    festival_type: 'Hindu / Ritual',
    significance: 'Not one festival but 400+ forms of ancient ritual possession-dance performed in village shrines across North Kerala (Kannur, Kasaragod). Performers embody deities in extraordinary costumes, fire rituals, and oracle pronouncements. One of the world\'s great living ritual traditions.',
    crowd_level: 'low',
    travel_impact: 'Performances scattered across remote village shrines. No mass tourism infrastructure. Intimate and authentic.',
    notes: 'Requires a knowledgeable local guide to locate performances and navigate protocol. Deeply powerful — unlike anything else on Earth. Kannur is the base. Not combinable with South Kerala in a short trip.',
    recurring: true
  },

  // ── CHUNK 3 ADDITIONS ────────────────────────────────────────────────────
  {
    name: 'Ganesh Chaturthi',
    local_name: 'Ganeshotsav',
    start_date: '2026-09-06',
    end_date: '2026-09-16',
    city: 'Mumbai',
    region: 'Maharashtra',
    state: 'Maharashtra',
    festival_type: 'Hindu',
    significance: '10-day festival honouring Ganesha. Massive clay idols in homes and public pandals across Maharashtra. Climaxes with Anant Chaturdashi sea immersion procession. Mumbai\'s Lalbaugcha Raja draws millions. Pune equally spectacular.',
    crowd_level: 'very high',
    travel_impact: 'Mumbai transport severely impacted on immersion day (Day 10). Roads blocked for processions. BST guests arrive Sep 3 — festival begins Sep 6, fully overlapping the itinerary.',
    notes: 'BST OVERLAP: must incorporate into BST Mumbai itinerary. Immersion procession on final day is extraordinary. Best viewed from upper floors or a guided vantage point.',
    recurring: true
  },
  {
    name: 'Janmashtami',
    local_name: 'Krishna Jayanti',
    start_date: '2026-09-03',
    end_date: '2026-09-04',
    city: 'Mathura',
    region: 'Braj Mandal',
    state: 'Uttar Pradesh',
    festival_type: 'Hindu / Vaishnava',
    significance: 'Birth of Krishna celebrated at midnight. Mathura (birthplace) and Vrindavan are the epicentres of a 5-day celebration. Mumbai\'s Dahi Handi features competitive human pyramids to break a clay pot of yogurt.',
    crowd_level: 'very high',
    travel_impact: 'Mathura-Vrindavan corridor overwhelmed. Midnight events mean all-night operations. Mumbai Dahi Handi draws enormous street crowds.',
    notes: 'BST ARRIVAL DAY = Janmashtami. BUILD FIRST BST NIGHT AROUND THIS. ISKCON Vrindavan temple is the most atmospheric. Midnight celebration at Krishna Janmabhoomi temple is the spiritual centrepiece.',
    recurring: true
  },
  {
    name: 'Ziro Music Festival',
    local_name: null,
    start_date: '2026-09-24',
    end_date: '2026-09-27',
    city: 'Ziro Valley',
    region: 'Arunachal Pradesh',
    state: 'Arunachal Pradesh',
    festival_type: 'Cultural / Music',
    significance: 'India\'s premier outdoor indie and folk music festival set among the terraced paddy fields and bamboo groves of the Apatani tribal heartland. Eco-conscious, intimate, and consistently rated among Asia\'s best music festivals.',
    crowd_level: 'medium',
    travel_impact: 'Inner Line Permit (ILP) required for non-Arunachal residents — obtain in advance. Itanagar is the nearest city. Limited accommodation; camping is the primary option.',
    notes: 'BST-adjacent dates. Outstanding for culturally adventurous clients. Ziro Valley is a UNESCO Tentative World Heritage Site. Combine with Tawang monastery for a full Arunachal itinerary.',
    recurring: true
  },
  {
    name: 'Durga Puja',
    local_name: 'Mahalaya to Bijoya Dashami',
    start_date: '2026-10-15',
    end_date: '2026-10-19',
    city: 'Kolkata',
    region: 'West Bengal',
    state: 'West Bengal',
    festival_type: 'Hindu',
    significance: 'Kolkata\'s greatest festival — the city becomes an open-air art gallery. Thousands of elaborately themed pandals with monumental Durga idols. Private pandal tours available with curators. Climaxes with immersion (Bisarjan) in the Hooghly River. UNESCO Intangible Cultural Heritage (2021).',
    crowd_level: 'very high',
    travel_impact: 'Kolkata hotels completely sold out 6 months ahead. City never sleeps for 5 days. All transport stretched.',
    notes: 'Book private pandal-hopping guide for curated access. Heritage neighbourhoods (Kumartuli potters\' quarter, North Kolkata) offer the most authentic atmosphere. Non-negotiable for any Oct Kolkata visit.',
    recurring: true
  },
  {
    name: 'Navratri Sharada',
    local_name: 'Sharad Navratri',
    start_date: '2026-10-11',
    end_date: '2026-10-19',
    city: null,
    region: 'Nationwide — especially Gujarat',
    state: 'All India',
    festival_type: 'Hindu',
    significance: 'Nine nights of Goddess Durga worship in her nine forms. Gujarat\'s Garba (circle dance) is UNESCO Intangible Cultural Heritage — all-night dancing for 9 consecutive nights in Ahmedabad, Vadodara, and Surat. Kolkata\'s Durga Puja is the culmination.',
    crowd_level: 'very high',
    travel_impact: 'Gujarat cities festive and crowded nightly. Domestic flights surge. Hotels at premium across Ahmedabad, Vadodara, and Kolkata.',
    notes: 'Two distinct experiences: Gujarat (all-night Garba dancing, spectacular costumes) vs Kolkata (artistic pandals, cultural performances). Both extraordinary. Dussehra on the 10th day.',
    recurring: true
  },

  // ── CHUNK 2 ADDITIONS ────────────────────────────────────────────────────
  {
    name: 'Thrissur Pooram',
    local_name: null,
    start_date: '2026-04-29',
    end_date: '2026-04-30',
    city: 'Thrissur',
    region: 'Central Kerala',
    state: 'Kerala',
    festival_type: 'Hindu / Temple',
    significance: '30+ caparisoned elephants from rival temples face off in a display of parasols, whisks, and fans to the beat of thunderous panchavadyam percussion. Called the festival that the gods themselves attend. Climaxes with a spectacular fireworks display at dawn.',
    crowd_level: 'very high',
    travel_impact: 'Thrissur city brought to a standstill. Over a million spectators. Book Kochi and Thrissur accommodation months ahead.',
    notes: 'One of India\'s most spectacular events and a non-negotiable for any Kerala itinerary timed in April-May. Exact date set annually by the Vadakkunathan temple.',
    recurring: true
  },
  {
    name: 'Bihu Rongali',
    local_name: 'Rongali Bihu / Bohag Bihu',
    start_date: '2026-04-14',
    end_date: '2026-04-20',
    city: null,
    region: 'Assam',
    state: 'Assam',
    festival_type: 'Hindu / Harvest',
    significance: 'Assamese New Year and spring harvest festival. Bihu dancers perform in fields, public spaces, and competitions across the state. Feasting on pitha (rice cakes) and laru. Entire Assam comes alive with music and colour.',
    crowd_level: 'medium',
    travel_impact: 'Guwahati and Jorhat festive. Brahmaputra river cruises well-timed. Domestic travel increases.',
    notes: 'Pairs perfectly with a Kaziranga rhino safari — the park is at its best in April before the monsoon.',
    recurring: true
  },
  {
    name: 'Hemis Festival',
    local_name: null,
    start_date: '2026-06-19',
    end_date: '2026-06-20',
    city: 'Hemis',
    region: 'Ladakh',
    state: 'Ladakh',
    festival_type: 'Buddhist / Tibetan',
    significance: 'Hemis Monastery\'s annual celebration of Guru Padmasambhava\'s birthday. Monks in elaborate costumes perform Cham masked dances against a dramatic Himalayan backdrop. The largest monastic festival in Ladakh.',
    crowd_level: 'medium',
    travel_impact: 'Leh hotels fill. Hemis village road-access restricted on festival days. Acclimatisation (2-3 days in Leh) is essential before attending.',
    notes: 'Every 12 years the giant Thangka is unfurled (next: 2029). Combine with Pangong Lake, Nubra Valley, and Zanskar for a full Ladakh journey.',
    recurring: true
  },
  {
    name: 'Rath Yatra Puri',
    local_name: 'Chariot Festival of Lord Jagannath',
    start_date: '2026-06-28',
    end_date: '2026-07-07',
    city: 'Puri',
    region: 'Odisha Coast',
    state: 'Odisha',
    festival_type: 'Hindu / Vaishnava',
    significance: 'Lord Jagannath, Balabhadra, and Subhadra are pulled through the streets of Puri on three massive wooden chariots by hundreds of thousands of devotees. The original "juggernaut." UNESCO-recognised intangible cultural heritage. Over 1 million pilgrims.',
    crowd_level: 'very high',
    travel_impact: 'Puri overwhelmed. All accommodation books out months ahead. Puri-Bhubaneswar road congested throughout.',
    notes: 'The chariot procession takes 2-3 days to travel 3km. Exact date determined by the Odia lunar calendar — confirm annually. Combine with Konark Sun Temple and Chilika Lake.',
    recurring: true
  },
  {
    name: 'Nehru Trophy Boat Race',
    local_name: null,
    start_date: '2026-08-08',
    end_date: '2026-08-08',
    city: 'Alappuzha',
    region: 'Kerala Backwaters',
    state: 'Kerala',
    festival_type: 'Cultural / Sport',
    significance: 'India\'s most famous snake boat race (vallam kali). Massive chundan vallams (snake boats) crewed by 100+ rowers race across Punnamada Lake to the beat of vanchipattu (boat songs). A breathtaking display of synchronised rowing power.',
    crowd_level: 'very high',
    travel_impact: 'Alappuzha houseboat stays and lakeside hotels book out months ahead. Spectator viewpoints fill from dawn.',
    notes: 'Book a houseboat positioned on Punnamada Lake for the best race view. Pairs naturally with Kerala backwaters, Kumarakom, and Kochi.',
    recurring: true
  },

  // ── CHUNK 1 ADDITIONS ────────────────────────────────────────────────────
  {
    name: 'Lathmar Holi Barsana',
    local_name: null,
    start_date: '2026-02-28',
    end_date: '2026-03-01',
    city: 'Barsana',
    region: 'Braj Mandal',
    state: 'Uttar Pradesh',
    festival_type: 'Hindu / Cultural',
    significance: 'Women of Barsana beat men from Nandgaon with lathis (sticks) in a playful re-enactment of Krishna and Radha\'s legend. The most unique Holi celebration in India.',
    crowd_level: 'very high',
    travel_impact: 'Small town, enormous crowds. Base in Mathura or Agra and day-trip with a local guide.',
    notes: 'Day trip from Mathura. Spectacular for photography. Guests must be prepared for colour powder, noise, and tight crowds.',
    recurring: true
  },
  {
    name: 'Uttarayan Kite Festival',
    local_name: 'Uttarayan',
    start_date: '2026-01-14',
    end_date: '2026-01-15',
    city: 'Ahmedabad',
    region: 'Gujarat',
    state: 'Gujarat',
    festival_type: 'Hindu / Cultural',
    significance: 'International kite festival on Makar Sankranti. Skies over Ahmedabad and across Gujarat blanketed with kites of every colour. Night kiting (patang with lights) on the evening of Jan 14 is especially magical.',
    crowd_level: 'very high',
    travel_impact: 'Ahmedabad hotels book out weeks and months ahead. Rooftop access is the premium commodity. Book early.',
    notes: 'Best experienced from a rooftop with local hosts. Combines well with Rann of Kutch if timed around Rann Utsav.',
    recurring: true
  },
  {
    name: 'Goa Carnival',
    local_name: 'Carnaval de Goa',
    start_date: '2026-02-14',
    end_date: '2026-02-17',
    city: 'Panaji',
    region: 'Goa',
    state: 'Goa',
    festival_type: 'Catholic / Cultural',
    significance: 'Portuguese colonial heritage carnival — float parades, King Momo, the iconic Red and Black dance (Clube Nacional), music, and street revelry across Panaji, Margao, Mapusa, and Vasco.',
    crowd_level: 'medium',
    travel_impact: 'Goa in peak season — accommodation available but filling. A festive and easy-going atmosphere.',
    notes: 'Unique fusion of Indian and Lusophone cultures. The Red and Black ball in Panaji is the social highlight.',
    recurring: true
  },
  {
    name: 'Desert Festival',
    local_name: null,
    start_date: '2026-02-09',
    end_date: '2026-02-11',
    city: 'Jaisalmer',
    region: 'Rajasthan',
    state: 'Rajasthan',
    festival_type: 'Cultural / Tourism',
    significance: 'Three-day Rajasthani folk festival on the Sam sand dunes outside Jaisalmer. Folk music (Manganiyar, Langa), camel races, turban-tying contests, and the popular Mr Desert contest.',
    crowd_level: 'high',
    travel_impact: 'Jaisalmer hotels and desert camps fill rapidly. Book dune camps far ahead.',
    notes: 'Natural fit for Rajasthan itineraries. Timed around the February full moon. Pairs well with Bikaner Camel Festival.',
    recurring: true
  }

];

async function seedFestivals() {
  const client = await pool.connect();
  try {
    let inserted = 0;
    let skipped = 0;
    for (const f of festivals) {
      const result = await client.query(
        `INSERT INTO festivals
          (name, local_name, start_date, end_date, city, region, state,
           festival_type, significance, crowd_level, travel_impact, notes, recurring)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
         ON CONFLICT (name, start_date) DO NOTHING`,
        [
          f.name, f.local_name, f.start_date, f.end_date,
          f.city, f.region, f.state, f.festival_type,
          f.significance, f.crowd_level, f.travel_impact,
          f.notes, f.recurring
        ]
      );
      if (result.rowCount > 0) inserted++;
      else skipped++;
    }
    console.log(`Done — ${inserted} inserted, ${skipped} already existed.`);
  } finally {
    client.release();
    await pool.end();
  }
}

seedFestivals().catch(console.error);
